#ifndef DEFINES_H
#define DEFINES_H

// Input Size
#define SEQUENCE_LENGTH 120  // Assuming your input shape is (120, 1)
#define INPUT_CHANNELS 1

#define CONV1D_KERNEL_SIZE 3
#define CONV1D_INPUT_CHANNELS 1
#define CONV1D_FILTERS 16
#define CONV1D_BIAS_SIZE 16
#define CONV1D_OUTPUT_SIZE 118

#define BATCH_NORMALIZATION_CHANNELS 16

#define MAX_POOLING1D_POOL_SIZE 2
#define MAX_POOLING1D_STRIDE 2
#define MAX_POOLING1D_OUTPUT_SIZE 59

#define CONV1D_1_KERNEL_SIZE 3
#define CONV1D_1_INPUT_CHANNELS 16
#define CONV1D_1_FILTERS 32
#define CONV1D_1_BIAS_SIZE 32
#define CONV1D_1_OUTPUT_SIZE 57

#define BATCH_NORMALIZATION_1_CHANNELS 32

#define MAX_POOLING1D_1_POOL_SIZE 2
#define MAX_POOLING1D_1_STRIDE 2
#define MAX_POOLING1D_1_OUTPUT_SIZE 28

#define DENSE_INPUT_SIZE 896
#define DENSE_OUTPUT_SIZE 64

#define BATCH_NORMALIZATION_2_CHANNELS 64

#define DENSE_1_INPUT_SIZE 64
#define DENSE_1_OUTPUT_SIZE 32

#define BATCH_NORMALIZATION_3_CHANNELS 32

#define DENSE_2_INPUT_SIZE 32
#define DENSE_2_OUTPUT_SIZE 20

#endif
