Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    batch_normalization:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      Trace: false
    batch_normalization_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      Trace: false
    batch_normalization_2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      Trace: false
    batch_normalization_3:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      Trace: false
    conv1d:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv1d_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv1d_1_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv1d_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_1_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_2_softmax:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    flatten:
      Precision:
        result: fixed<16,6>
      Trace: false
    input_1:
      Precision:
        result: fixed<16,6>
      Trace: false
    max_pooling1d:
      Precision:
        result: fixed<16,6>
      Trace: false
    max_pooling1d_1:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls4ml_prj/keras_model.h5'
OutputDir: hls4ml_prj
OutputPredictions: null
Part: xczu3eg-sbva484-2-i
ProjectName: myproject
Stamp: 70b7E55C
Version: 1.0.0
