// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gesture_model_dense_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [9:0] input_r_address0;
output   input_r_ce0;
input  [23:0] input_r_q0;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [22:0] output_r_d0;

reg ap_idle;
reg input_r_ce0;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln88_fu_179_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] dense_0_biases_V_address0;
reg    dense_0_biases_V_ce0;
wire   [16:0] dense_0_biases_V_q0;
wire   [13:0] dense_0_weights_V_address0;
reg    dense_0_weights_V_ce0;
wire  signed [17:0] dense_0_weights_V_q0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln91_fu_203_p2;
reg   [0:0] icmp_ln91_reg_606;
reg   [0:0] icmp_ln91_reg_606_pp0_iter1_reg;
reg   [0:0] icmp_ln91_reg_606_pp0_iter2_reg;
reg   [0:0] icmp_ln91_reg_606_pp0_iter3_reg;
wire   [4:0] select_ln88_1_fu_217_p3;
reg   [4:0] select_ln88_1_reg_611;
reg   [4:0] select_ln88_1_reg_611_pp0_iter1_reg;
reg   [4:0] select_ln88_1_reg_611_pp0_iter2_reg;
reg   [4:0] select_ln88_1_reg_611_pp0_iter3_reg;
wire   [0:0] ifzero_fu_259_p2;
reg   [0:0] ifzero_reg_626;
reg   [0:0] ifzero_reg_626_pp0_iter1_reg;
reg   [0:0] ifzero_reg_626_pp0_iter2_reg;
reg   [0:0] ifzero_reg_626_pp0_iter3_reg;
reg   [0:0] ifzero_reg_626_pp0_iter4_reg;
wire   [63:0] zext_ln88_fu_291_p1;
reg   [63:0] zext_ln88_reg_640;
wire  signed [23:0] sum_V_fu_434_p3;
reg  signed [23:0] sum_V_reg_645;
wire   [63:0] zext_ln1273_fu_248_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] j_cast_fu_229_p1;
reg   [23:0] lhs_fu_88;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
reg    ap_loop_init_pp0_iter2_reg;
reg    ap_loop_init_pp0_iter3_reg;
reg    ap_loop_init_pp0_iter4_reg;
reg   [23:0] ap_sig_allocacmp_lhs_load;
reg   [9:0] j_fu_92;
wire   [9:0] add_ln91_fu_253_p2;
reg   [9:0] ap_sig_allocacmp_j_load;
reg   [4:0] i_fu_96;
reg   [4:0] ap_sig_allocacmp_i_load;
reg   [13:0] indvar_flatten_fu_100;
wire   [13:0] add_ln88_1_fu_185_p2;
reg   [13:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [4:0] add_ln88_fu_197_p2;
wire   [9:0] select_ln88_fu_209_p3;
wire   [13:0] tmp_s_fu_234_p3;
wire   [13:0] select_ln88_1_cast_fu_225_p1;
wire   [13:0] add_ln1273_fu_242_p2;
wire   [23:0] select_ln88_2_fu_295_p3;
wire  signed [41:0] lhs_1_fu_302_p3;
wire  signed [41:0] grp_fu_566_p2;
wire  signed [42:0] sext_ln1347_1_fu_314_p1;
wire  signed [42:0] sext_ln1347_fu_310_p1;
wire   [42:0] ret_V_2_fu_322_p2;
(* use_dsp48 = "no" *) wire   [41:0] add_ln1347_fu_317_p2;
wire   [0:0] p_Result_38_fu_346_p3;
wire   [0:0] tmp_fu_354_p3;
wire   [0:0] p_Result_37_fu_328_p3;
wire   [0:0] or_ln895_fu_362_p2;
wire   [0:0] xor_ln895_4_fu_368_p2;
wire   [0:0] and_ln896_fu_380_p2;
wire   [22:0] tmp_3_fu_392_p4;
wire   [0:0] icmp_ln900_4_fu_402_p2;
wire   [0:0] xor_ln896_17_fu_386_p2;
wire   [0:0] or_ln898_17_fu_408_p2;
wire   [0:0] overflow_3_fu_374_p2;
wire   [0:0] underflow_3_fu_414_p2;
wire   [0:0] or_ln346_17_fu_428_p2;
wire   [23:0] select_ln346_fu_420_p3;
wire   [23:0] sum_V_2_fu_336_p4;
wire  signed [24:0] sext_ln813_fu_447_p1;
wire   [24:0] zext_ln813_fu_454_p1;
wire   [24:0] ret_V_fu_458_p2;
wire   [23:0] dense_0_biases_V_load_cast_fu_450_p1;
wire   [23:0] p_Val2_16_fu_472_p2;
wire   [0:0] p_Result_s_fu_464_p3;
wire   [0:0] p_Result_36_fu_477_p3;
wire   [0:0] xor_ln895_fu_485_p2;
wire   [22:0] trunc_ln900_fu_503_p1;
wire   [0:0] icmp_ln900_fu_507_p2;
wire   [0:0] xor_ln896_fu_497_p2;
wire   [0:0] or_ln898_fu_513_p2;
wire   [0:0] overflow_fu_491_p2;
wire   [0:0] underflow_fu_519_p2;
wire   [0:0] or_ln346_fu_533_p2;
wire   [23:0] select_ln346_35_fu_525_p3;
wire   [23:0] x_V_fu_539_p3;
wire   [0:0] icmp_ln1649_fu_551_p2;
wire   [22:0] trunc_ln17_fu_547_p1;
reg    grp_fu_566_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_184;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
end

gesture_model_dense_0_dense_0_biases_V_ROM_AUTO_1R #(
    .DataWidth( 17 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
dense_0_biases_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_0_biases_V_address0),
    .ce0(dense_0_biases_V_ce0),
    .q0(dense_0_biases_V_q0)
);

gesture_model_dense_0_dense_0_weights_V_ROM_AUTO_1R #(
    .DataWidth( 18 ),
    .AddressRange( 15104 ),
    .AddressWidth( 14 ))
dense_0_weights_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_0_weights_V_address0),
    .ce0(dense_0_weights_V_ce0),
    .q0(dense_0_weights_V_q0)
);

gesture_model_mul_mul_24s_18s_42_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 42 ))
mul_mul_24s_18s_42_4_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(input_r_q0),
    .din1(dense_0_weights_V_q0),
    .ce(grp_fu_566_ce),
    .dout(grp_fu_566_p2)
);

gesture_model_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_184)) begin
        if ((icmp_ln88_fu_179_p2 == 1'd0)) begin
            i_fu_96 <= select_ln88_1_fu_217_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_96 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_184)) begin
        if ((icmp_ln88_fu_179_p2 == 1'd0)) begin
            indvar_flatten_fu_100 <= add_ln88_1_fu_185_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_100 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_184)) begin
        if ((icmp_ln88_fu_179_p2 == 1'd0)) begin
            j_fu_92 <= add_ln91_fu_253_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_92 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        lhs_fu_88 <= sum_V_fu_434_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        ap_loop_init_pp0_iter2_reg <= ap_loop_init_pp0_iter1_reg;
        icmp_ln91_reg_606_pp0_iter1_reg <= icmp_ln91_reg_606;
        ifzero_reg_626_pp0_iter1_reg <= ifzero_reg_626;
        select_ln88_1_reg_611_pp0_iter1_reg <= select_ln88_1_reg_611;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_init_pp0_iter3_reg <= ap_loop_init_pp0_iter2_reg;
        ap_loop_init_pp0_iter4_reg <= ap_loop_init_pp0_iter3_reg;
        icmp_ln91_reg_606_pp0_iter2_reg <= icmp_ln91_reg_606_pp0_iter1_reg;
        icmp_ln91_reg_606_pp0_iter3_reg <= icmp_ln91_reg_606_pp0_iter2_reg;
        ifzero_reg_626_pp0_iter2_reg <= ifzero_reg_626_pp0_iter1_reg;
        ifzero_reg_626_pp0_iter3_reg <= ifzero_reg_626_pp0_iter2_reg;
        ifzero_reg_626_pp0_iter4_reg <= ifzero_reg_626_pp0_iter3_reg;
        select_ln88_1_reg_611_pp0_iter2_reg <= select_ln88_1_reg_611_pp0_iter1_reg;
        select_ln88_1_reg_611_pp0_iter3_reg <= select_ln88_1_reg_611_pp0_iter2_reg;
        sum_V_reg_645 <= sum_V_fu_434_p3;
        zext_ln88_reg_640[4 : 0] <= zext_ln88_fu_291_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln88_fu_179_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln91_reg_606 <= icmp_ln91_fu_203_p2;
        ifzero_reg_626 <= ifzero_fu_259_p2;
        select_ln88_1_reg_611 <= select_ln88_1_fu_217_p3;
    end
end

always @ (*) begin
    if (((icmp_ln88_fu_179_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 5'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 14'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 10'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_loop_init_pp0_iter4_reg == 1'b1))) begin
        ap_sig_allocacmp_lhs_load = 24'd0;
    end else begin
        ap_sig_allocacmp_lhs_load = lhs_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        dense_0_biases_V_ce0 = 1'b1;
    end else begin
        dense_0_biases_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dense_0_weights_V_ce0 = 1'b1;
    end else begin
        dense_0_weights_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_566_ce = 1'b1;
    end else begin
        grp_fu_566_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (ifzero_reg_626_pp0_iter4_reg == 1'd1))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1273_fu_242_p2 = (tmp_s_fu_234_p3 + select_ln88_1_cast_fu_225_p1);

assign add_ln1347_fu_317_p2 = ($signed(grp_fu_566_p2) + $signed(lhs_1_fu_302_p3));

assign add_ln88_1_fu_185_p2 = (ap_sig_allocacmp_indvar_flatten_load + 14'd1);

assign add_ln88_fu_197_p2 = (ap_sig_allocacmp_i_load + 5'd1);

assign add_ln91_fu_253_p2 = (select_ln88_fu_209_p3 + 10'd1);

assign and_ln896_fu_380_p2 = (tmp_fu_354_p3 & p_Result_38_fu_346_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_184 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign dense_0_biases_V_address0 = zext_ln88_fu_291_p1;

assign dense_0_biases_V_load_cast_fu_450_p1 = dense_0_biases_V_q0;

assign dense_0_weights_V_address0 = zext_ln1273_fu_248_p1;

assign icmp_ln1649_fu_551_p2 = (($signed(x_V_fu_539_p3) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_179_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 14'd15104) ? 1'b1 : 1'b0);

assign icmp_ln900_4_fu_402_p2 = ((tmp_3_fu_392_p4 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln900_fu_507_p2 = ((trunc_ln900_fu_503_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_203_p2 = ((ap_sig_allocacmp_j_load == 10'd944) ? 1'b1 : 1'b0);

assign ifzero_fu_259_p2 = ((add_ln91_fu_253_p2 == 10'd944) ? 1'b1 : 1'b0);

assign input_r_address0 = j_cast_fu_229_p1;

assign j_cast_fu_229_p1 = select_ln88_fu_209_p3;

assign lhs_1_fu_302_p3 = {{select_ln88_2_fu_295_p3}, {18'd0}};

assign or_ln346_17_fu_428_p2 = (underflow_3_fu_414_p2 | overflow_3_fu_374_p2);

assign or_ln346_fu_533_p2 = (underflow_fu_519_p2 | overflow_fu_491_p2);

assign or_ln895_fu_362_p2 = (tmp_fu_354_p3 | p_Result_38_fu_346_p3);

assign or_ln898_17_fu_408_p2 = (xor_ln896_17_fu_386_p2 | icmp_ln900_4_fu_402_p2);

assign or_ln898_fu_513_p2 = (xor_ln896_fu_497_p2 | icmp_ln900_fu_507_p2);

assign output_r_address0 = zext_ln88_reg_640;

assign output_r_d0 = ((icmp_ln1649_fu_551_p2[0:0] == 1'b1) ? trunc_ln17_fu_547_p1 : 23'd0);

assign overflow_3_fu_374_p2 = (xor_ln895_4_fu_368_p2 & or_ln895_fu_362_p2);

assign overflow_fu_491_p2 = (xor_ln895_fu_485_p2 & p_Result_36_fu_477_p3);

assign p_Result_36_fu_477_p3 = p_Val2_16_fu_472_p2[32'd23];

assign p_Result_37_fu_328_p3 = ret_V_2_fu_322_p2[32'd42];

assign p_Result_38_fu_346_p3 = add_ln1347_fu_317_p2[32'd41];

assign p_Result_s_fu_464_p3 = ret_V_fu_458_p2[32'd24];

assign p_Val2_16_fu_472_p2 = ($signed(sum_V_reg_645) + $signed(dense_0_biases_V_load_cast_fu_450_p1));

assign ret_V_2_fu_322_p2 = ($signed(sext_ln1347_1_fu_314_p1) + $signed(sext_ln1347_fu_310_p1));

assign ret_V_fu_458_p2 = ($signed(sext_ln813_fu_447_p1) + $signed(zext_ln813_fu_454_p1));

assign select_ln346_35_fu_525_p3 = ((overflow_fu_491_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388609);

assign select_ln346_fu_420_p3 = ((overflow_3_fu_374_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388609);

assign select_ln88_1_cast_fu_225_p1 = select_ln88_1_fu_217_p3;

assign select_ln88_1_fu_217_p3 = ((icmp_ln91_fu_203_p2[0:0] == 1'b1) ? add_ln88_fu_197_p2 : ap_sig_allocacmp_i_load);

assign select_ln88_2_fu_295_p3 = ((icmp_ln91_reg_606_pp0_iter3_reg[0:0] == 1'b1) ? 24'd0 : ap_sig_allocacmp_lhs_load);

assign select_ln88_fu_209_p3 = ((icmp_ln91_fu_203_p2[0:0] == 1'b1) ? 10'd0 : ap_sig_allocacmp_j_load);

assign sext_ln1347_1_fu_314_p1 = grp_fu_566_p2;

assign sext_ln1347_fu_310_p1 = lhs_1_fu_302_p3;

assign sext_ln813_fu_447_p1 = sum_V_reg_645;

assign sum_V_2_fu_336_p4 = {{add_ln1347_fu_317_p2[41:18]}};

assign sum_V_fu_434_p3 = ((or_ln346_17_fu_428_p2[0:0] == 1'b1) ? select_ln346_fu_420_p3 : sum_V_2_fu_336_p4);

assign tmp_3_fu_392_p4 = {{add_ln1347_fu_317_p2[40:18]}};

assign tmp_fu_354_p3 = ret_V_2_fu_322_p2[32'd42];

assign tmp_s_fu_234_p3 = {{select_ln88_fu_209_p3}, {4'd0}};

assign trunc_ln17_fu_547_p1 = x_V_fu_539_p3[22:0];

assign trunc_ln900_fu_503_p1 = p_Val2_16_fu_472_p2[22:0];

assign underflow_3_fu_414_p2 = (p_Result_37_fu_328_p3 & or_ln898_17_fu_408_p2);

assign underflow_fu_519_p2 = (p_Result_s_fu_464_p3 & or_ln898_fu_513_p2);

assign x_V_fu_539_p3 = ((or_ln346_fu_533_p2[0:0] == 1'b1) ? select_ln346_35_fu_525_p3 : p_Val2_16_fu_472_p2);

assign xor_ln895_4_fu_368_p2 = (p_Result_37_fu_328_p3 ^ 1'd1);

assign xor_ln895_fu_485_p2 = (p_Result_s_fu_464_p3 ^ 1'd1);

assign xor_ln896_17_fu_386_p2 = (1'd1 ^ and_ln896_fu_380_p2);

assign xor_ln896_fu_497_p2 = (p_Result_36_fu_477_p3 ^ 1'd1);

assign zext_ln1273_fu_248_p1 = add_ln1273_fu_242_p2;

assign zext_ln813_fu_454_p1 = dense_0_biases_V_q0;

assign zext_ln88_fu_291_p1 = select_ln88_1_reg_611_pp0_iter3_reg;

always @ (posedge ap_clk) begin
    zext_ln88_reg_640[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //gesture_model_dense_0
